# .travis.yml
dist: precise

language: php

php:
- 7.3

cache:
  directories:
  - node_modules
  - vendor

before_script:
- composer self-update
- composer install --no-interaction

script:
- vendor/bin/phpunit
