<?php

namespace Pagevamp\Tests;

use Illuminate\Container\Container;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Storage;
use Orchestra\Testbench\TestCase;

class AbstractTestCase extends TestCase
{
    // Here you can add global testing functions
    protected $storage;

    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        $app = new Container();
        $app->singleton('app', 'Illuminate\Container\Container');

        $app->singleton('config', 'Illuminate\Config\Repository');

        $this->storage = Storage::disk('public');

        $app->instance('path.config', app()->basePath() . DIRECTORY_SEPARATOR . 'config');
        $app->instance('path.storage', app()->basePath() . DIRECTORY_SEPARATOR . 'storage');


        Config::shouldReceive('get')
            ->with('storage.driver.media')
            ->andReturn('public');


    }
}
